project_id = "bamexkkbepzlvaybysui"

[functions.execute-code]
verify_jwt = true

[functions.admin-create-user]
verify_jwt = true

[functions.cleanup-duplicates]
verify_jwt = true

[functions.generate-daily-challenges]
verify_jwt = false

[functions.grade-exam-background]
verify_jwt = true
